// ─── THEME 
export const THEMES = {
  primary: "#0D9488",
  accent:  "#F97316",
  gold:    "#F59E0B",
  teal:    "#0D9488",
  navy:    "#0F172A",
};

// ─── DROPDOWN OPTIONS 
export const OPTIONS = {

  // Shared
  gender:       ["Male", "Female", "Other"],
  degree_type:  ["UG", "PG", "PhD"],
  school: [
    "Goa Business School",
    
  ],
  discipline: [
    "Management Studies",
    "Economics",
    "Commerce",
    "Computer Science & Technology",
    
  ],
  sector: [
    "IT", "Finance", "Tourism", "Research", "Education",
    "Healthcare", "Government", "Manufacturing",
    "Media & Communication", "Agriculture", "Other",
  ],
  skills_list: [
    // Technical
    "MS Office",
    "Tally & Accounting Software",
    "GST & Taxation",
    "Financial Modelling",
    "Data Analysis",
    "Python Programming",
    "Java Programming",
    "C / C++",
    "Web Development",
    "Database Management (SQL)",
    "Graphic Design",
    "Video Editing",
    // Soft Skills
    "Communication Skills",
    "Leadership",
    "Teamwork & Collaboration",
    "Problem Solving",
    "Critical Thinking",
    "Time Management",
    "Public Speaking",
    "Adaptability",
    // Domain
    "Research & Analysis",
    "Content Writing",
    "Digital Marketing",
    "Social Media Management",
    "Tourism & Hospitality Management",
    "Legal Research",
    "Teaching & Mentoring",
    "Event Management",
  ],

  // Student only
  category:     ["General", "OBC", "SC", "ST"],
  taluka: [
    "Panaji", "Tiswadi", "Bardez", "Pernem", "Bicholim", "Sattari",
    "Ponda", "Mormugao", "Salcete", "Quepem", "Sanguem", "Canacona",
  ],
  district:              ["North Goa", "South Goa"],
  year_of_passing_student: ["2020", "2021", "2022", "2023", "2024", "2025"],
  aspirational_sector:   ["IT", "Finance", "Tourism", "Research", "Education", "Healthcare", "Government", "Entrepreneurship", "Other"],
  entrepreneurship_inclination: ["Yes", "No"],

  // Alumni only
  year_of_passing_alumni: ["2015","2016","2017","2018","2019","2020","2021","2022","2023","2024","2025"],
  employment_type:        ["Private Sector", "Government", "Self-Employed", "Freelance", "Not Employed"],
  salary: [
    "Below 2 LPA", "2-5 LPA", "5-8 LPA",
    "8-12 LPA", "12-18 LPA", "18 LPA+", "Prefer not to say",
  ],
  location:              ["Goa", "Mumbai", "Pune", "Bengaluru", "Delhi", "Hyderabad", "Chennai", "Abroad", "Other"],
  years_of_experience:   ["Less than 1 year", "1-2 years", "3-5 years", "5-8 years", "8+ years"],
  higher_education:      ["Yes", "No"],
  skill_gap_perceived:   ["Yes, significant gap", "Somewhat", "No, well prepared"],
  would_recommend_goa_jobs: ["Yes", "No", "Maybe"],
};

// ─── MOCK STUDENT DATA 
export const STUDENTS = [
  {
    id: 1,
    enrollment_no:                "GU2024001",
    name:                         "Priya Naik",
    email:                        "priya@gmail.com",
    phone:                        "9876543210",
    gender:                       "Female",
    date_of_birth:                "2002-06-14",
    category:                     "OBC",
    taluka:                       "Panaji",
    district:                     "North Goa",
    degree_type:                  "PG",
    school:                       "Goa Business School",
    discipline:                   "Commerce",
    course:                       "MBA",
    year_of_passing:              "2024",
    aspirational_sector:          "Finance",
    entrepreneurship_inclination: "No",
    skills_possessed:             "MS Office, Tally & Accounting Software, GST & Taxation, Communication Skills",
  },
  {
    id: 2,
    enrollment_no:                "GU2023002",
    name:                         "Rohan Dessai",
    email:                        "rohan@gmail.com",
    phone:                        "9876543211",
    gender:                       "Male",
    date_of_birth:                "2001-03-22",
    category:                     "General",
    taluka:                       "Salcete",
    district:                     "South Goa",
    degree_type:                  "PG",
    school:                       "School of Computer Science & Technology",
    discipline:                   "Computer Science & Technology",
    course:                       "MCA",
    year_of_passing:              "2023",
    aspirational_sector:          "IT",
    entrepreneurship_inclination: "Yes",
    skills_possessed:             "Python Programming, Database Management (SQL), Web Development, Data Analysis, Problem Solving",
  },
  {
    id: 3,
    enrollment_no:                "GU2024003",
    name:                         "Sneha Velip",
    email:                        "sneha@gmail.com",
    phone:                        "9876543212",
    gender:                       "Female",
    date_of_birth:                "2000-11-05",
    category:                     "ST",
    taluka:                       "Mormugao",
    district:                     "South Goa",
    degree_type:                  "PG",
    school:                       "Goa Business School",
    discipline:                   "Management Studies",
    course:                       "MBA",
    year_of_passing:              "2024",
    aspirational_sector:          "Tourism",
    entrepreneurship_inclination: "No",
    skills_possessed:             "Digital Marketing, Communication Skills, Social Media Management, MS Office, Leadership",
  },
  {
    id: 4,
    enrollment_no:                "GU2022004",
    name:                         "Aditya Chari",
    email:                        "aditya@gmail.com",
    phone:                        "9876543213",
    gender:                       "Male",
    date_of_birth:                "2000-08-17",
    category:                     "General",
    taluka:                       "Ponda",
    district:                     "North Goa",
    degree_type:                  "PG",
    school:                       "Goa Business School",
    discipline:                   "Economics",
    course:                       "IMBA",
    year_of_passing:              "2022",
    aspirational_sector:          "Research",
    entrepreneurship_inclination: "No",
    skills_possessed:             "Research & Analysis, Critical Thinking, Content Writing, Problem Solving",
  },
  {
    id: 5,
    enrollment_no:                "GU2023005",
    name:                         "Meera Kamat",
    email:                        "meera@gmail.com",
    phone:                        "9876543214",
    gender:                       "Female",
    date_of_birth:                "2001-01-30",
    category:                     "OBC",
    taluka:                       "Bardez",
    district:                     "North Goa",
    degree_type:                  "PG",
    school:                       "School of Computer Science & Technology",
    discipline:                   "Computer Science & Technology",
    course:                       "MSC AI",
    year_of_passing:              "2023",
    aspirational_sector:          "IT",
    entrepreneurship_inclination: "Yes",
    skills_possessed:             "Java Programming, Database Management (SQL), Python Programming, Web Development, Leadership, Teamwork & Collaboration",
  },
  {
    id: 6,
    enrollment_no:                "GU2024006",
    name:                         "Vikas Redkar",
    email:                        "vikas@gmail.com",
    phone:                        "9876543215",
    gender:                       "Male",
    date_of_birth:                "2002-09-11",
    category:                     "General",
    taluka:                       "Canacona",
    district:                     "South Goa",
    degree_type:                  "PG",
    school:                       "Goa Business School",
    discipline:                   "Management Studies",
    course:                       "MBA",
    year_of_passing:              "2024",
    aspirational_sector:          "Finance",
    entrepreneurship_inclination: "Yes",
    skills_possessed:             "Financial Modelling, MS Office, Tally & Accounting Software, Public Speaking",
  },
  {
    id: 7,
    enrollment_no:                "GU2023007",
    name:                         "Tara Fernandes",
    email:                        "tara@gmail.com",
    phone:                        "9876543216",
    gender:                       "Female",
    date_of_birth:                "2001-05-28",
    category:                     "SC",
    taluka:                       "Tiswadi",
    district:                     "North Goa",
    degree_type:                  "PG",
    school:                       "Goa Business School",
    discipline:                   "Commerce",
    course:                       "IMBA",
    year_of_passing:              "2023",
    aspirational_sector:          "Education",
    entrepreneurship_inclination: "No",
    skills_possessed:             "GST & Taxation, Tally & Accounting Software, Communication Skills, Teaching & Mentoring",
  },
  {
    id: 8,
    enrollment_no:                "GU2024008",
    name:                         "Dev Shetye",
    email:                        "dev@gmail.com",
    phone:                        "9876543217",
    gender:                       "Male",
    date_of_birth:                "2002-12-03",
    category:                     "General",
    taluka:                       "Bicholim",
    district:                     "North Goa",
    degree_type:                  "PG",
    school:                       "School of Computer Science & Technology",
    discipline:                   "Computer Science & Technology",
    course:                       "MSC DS",
    year_of_passing:              "2024",
    aspirational_sector:          "IT",
    entrepreneurship_inclination: "Yes",
    skills_possessed:             "C / C++, Python Programming, Web Development, Problem Solving, Adaptability",
  },
];

// ─── MOCK ALUMNI DATA 
export const ALUMNI = [
  {
    id: 1,
    name:                     "Dr. Anjali Shet",
    email:                    "anjali.shet@gmail.com",
    phone:                    "9823456701",
    gender:                   "Female",
    enrollment_no:            "GU2019001",
    degree_type:              "PG",
    school:                   "Goa Business School",
    discipline:               "Economics",
    course:                   "M.Sc IDS",
    year_of_passing:          "2019",
    current_role:             "Research Scientist",
    company:                  "CSIR-NIO Goa",
    sector:                   "Research",
    employment_type:          "Government",
    salary:                   "8-12 LPA",
    location:                 "Goa",
    years_of_experience:      "5-8 years",
    higher_education:         "Yes",
    higher_education_details: "PhD in Marine Chemistry, Goa University",
    skill_gap_perceived:      "Somewhat",
    skills_used_at_work:      "Research & Analysis, Data Analysis, Content Writing, Critical Thinking",
    would_recommend_goa_jobs: "Yes",
    industry_feedback:        "More emphasis on practical lab research and industry collaboration would help graduates.",
  },
  {
    id: 2,
    name:                     "Kiran Naik",
    email:                    "kiran.naik@gmail.com",
    phone:                    "9823456702",
    gender:                   "Male",
    enrollment_no:            "GU2018002",
    degree_type:              "PG",
    school:                   "School of Computer Science & Technology",
    discipline:               "Computer Science & Technology",
    course:                   "MCA",
    year_of_passing:          "2018",
    current_role:             "Software Engineer",
    company:                  "Infosys",
    sector:                   "IT",
    employment_type:          "Private Sector",
    salary:                   "12-18 LPA",
    location:                 "Pune",
    years_of_experience:      "5-8 years",
    higher_education:         "No",
    higher_education_details: "",
    skill_gap_perceived:      "Yes, significant gap",
    skills_used_at_work:      "Python Programming, Java Programming, Database Management (SQL), Web Development, Problem Solving, Teamwork & Collaboration",
    would_recommend_goa_jobs: "No",
    industry_feedback:        "Industry needs more focus on cloud computing, DevOps and agile practices. University curriculum is outdated.",
  },
  {
    id: 3,
    name:                     "Sanjana Lotlikar",
    email:                    "sanjana.l@gmail.com",
    phone:                    "9823456703",
    gender:                   "Female",
    enrollment_no:            "GU2020003",
    degree_type:              "PG",
    school:                   "Goa Business School",
    discipline:               "Management Studies",
    course:                   "MBA",
    year_of_passing:          "2020",
    current_role:             "Marketing Manager",
    company:                  "Goa Tourism Board",
    sector:                   "Tourism",
    employment_type:          "Government",
    salary:                   "8-12 LPA",
    location:                 "Goa",
    years_of_experience:      "3-5 years",
    higher_education:         "No",
    higher_education_details: "",
    skill_gap_perceived:      "Somewhat",
    skills_used_at_work:      "Digital Marketing, Social Media Management, Communication Skills, Leadership, Event Management",
    would_recommend_goa_jobs: "Yes",
    industry_feedback:        "Tourism sector in Goa has great potential. Need more digital marketing and hospitality management training.",
  },
  {
    id: 4,
    name:                     "Rahul Borkar",
    email:                    "rahul.borkar@gmail.com",
    phone:                    "9823456704",
    gender:                   "Male",
    enrollment_no:            "GU2017004",
    degree_type:              "UPG",
    school:                   "Goa Business School",
    discipline:               "Computer Science & Technology",
    course:                   "MSC AI",
    year_of_passing:          "2017",
    current_role:             "Chartered Accountant",
    company:                  "Self-Employed",
    sector:                   "Finance",
    employment_type:          "Self-Employed",
    salary:                   "12-18 LPA",
    location:                 "Goa",
    years_of_experience:      "5-8 years",
    higher_education:         "Yes",
    higher_education_details: "CA from ICAI",
    skill_gap_perceived:      "No, well prepared",
    skills_used_at_work:      "GST & Taxation, Financial Modelling, Tally & Accounting Software, MS Office, Critical Thinking",
    would_recommend_goa_jobs: "Yes",
    industry_feedback:        "Commerce students are well prepared. More focus on GST and new age fintech would be beneficial.",
  },
  {
    id: 5,
    name:                     "Pooja Gaonkar",
    email:                    "pooja.gaonkar@gmail.com",
    phone:                    "9823456705",
    gender:                   "Female",
    enrollment_no:            "GU2021005",
    degree_type:              "PG",
    school:                   "Goa Business School",
    discipline:               "Computer Science & Technology",
    course:                   "MCA",
    year_of_passing:          "2021",
    current_role:             "UI/UX Designer",
    company:                  "TCS",
    sector:                   "IT",
    employment_type:          "Private Sector",
    salary:                   "8-12 LPA",
    location:                 "Bengaluru",
    years_of_experience:      "3-5 years",
    higher_education:         "No",
    higher_education_details: "",
    skill_gap_perceived:      "Yes, significant gap",
    skills_used_at_work:      "Graphic Design, Web Development, Communication Skills, Problem Solving, Adaptability",
    would_recommend_goa_jobs: "Maybe",
    industry_feedback:        "Design and UX skills are not taught at all. Students must self-learn to be industry ready.",
  },
  {
    id: 6,
    name:                     "Amit Padwalkar",
    email:                    "amit.p@gmail.com",
    phone:                    "9823456706",
    gender:                   "Male",
    enrollment_no:            "GU2016006",
    degree_type:              "PG",
    school:                   "School of Computer Science & Technology",
    discipline:               "Computer Science & Technology",
    course:                   "MCA",
    year_of_passing:          "2016",
    current_role:             "Operations Head",
    company:                  "Goa Shipyard Ltd",
    sector:                   "Manufacturing",
    employment_type:          "Government",
    salary:                   "18 LPA+",
    location:                 "Goa",
    years_of_experience:      "8+ years",
    higher_education:         "Yes",
    higher_education_details: "MBA Operations, Symbiosis Pune",
    skill_gap_perceived:      "Somewhat",
    skills_used_at_work:      "Leadership, Teamwork & Collaboration, Problem Solving, Time Management, Public Speaking",
    would_recommend_goa_jobs: "Yes",
    industry_feedback:        "Manufacturing sector needs more practical exposure and internships during the degree.",
  },
];